### ISSUE TITLE
lodash not found

### ISSUE THREAD

**Issue by mjvankampen** [egodigital/vscode-powertools#33]
I am getting an error with the extension. Am I required to install npm and such to install lodash?

```
[2020-01-28 09:40:28.770] [exthost] [error] Activating extension ego-digital.vscode-powertools failed due to an error:
[2020-01-28 09:40:28.772] [exthost] [error] Error: Cannot find module 'lodash'
Require stack:
- c:\Users\mjvk\.vscode\extensions\ego-digital.vscode-powertools-0.56.2\out\commands.js
- c:\Users\mjvk\.vscode\extensions\ego-digital.vscode-powertools-0.56.2\out\extension.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.Module._load (internal/modules/cjs/loader.js:531:27)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:851)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:164)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:618)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\mjvk\.vscode\extensions\ego-digital.vscode-powertools-0.56.2\out\commands.js:19:11)
	at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
	at Module.load (internal/modules/cjs/loader.js:645:32)
	at Function.Module._load (internal/modules/cjs/loader.js:560:12)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:851)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:164)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:618)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\mjvk\.vscode\extensions\ego-digital.vscode-powertools-0.56.2\out\extension.js:21:22)
	at Module.o._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
	at Module.load (internal/modules/cjs/loader.js:645:32)
	at Function.Module._load (internal/modules/cjs/loader.js:560:12)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:851)
	at Function.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:789:164)
	at Function.i._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:618)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at Function.s [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:32:963)
	at d._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:790:289)
	at d._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:694:547)
	at d._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:582)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:534)
	at d._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:21)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:516:632
	at Array.map (<anonymous>)
	at d._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:516:620)
	at d.activateById (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:514:709)
	at d._activateById (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:692:345)
	at d.$activate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:700:721)
```

**Comment by mjvankampen** [comment]
It seems my install was somehow corrupted. Removing vscode (including c:\Users\mjvk\.vscode\) and re-installing seemed to work.

**Comment by mjvankampen** [comment]
Something akin to https://github.com/microsoft/vscode/issues/43813
